# Generated by Django 4.0.6 on 2022-07-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(default='a', unique=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.SlugField(default='a', unique=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='featured',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='type',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
