# Generated by Django 4.0.6 on 2022-07-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_phone_slug_phone_updated_at_phone_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
