# Generated by Django 4.0.6 on 2022-07-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_phone_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
