# Generated by Django 4.0.6 on 2022-07-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_phone_slug_alter_type_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='best_selling',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='latest',
            field=models.BooleanField(default=True),
        ),
    ]
