# Generated by Django 4.0.6 on 2022-08-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_cart_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pix',
            field=models.ImageField(default='customer/avatar.jpg', upload_to='customer'),
        ),
    ]
