# Generated by Django 4.0.6 on 2022-08-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_alter_customer_pix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
