# Generated by Django 4.0.6 on 2022-08-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pix',
            field=models.ImageField(blank=True, default='customer/avatar.png', null=True, upload_to='customer'),
        ),
    ]
